apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:9tDLy2fzB+2kdoUSAlMvkZKK,iv:kRJetiXiQY9xEjhQ005Fx0GQB2tat1hmVmjLspZk9iE=,tag:KtsMJxNGYElLrmnGOqzsEA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:OmhsKufwpnC40P7z+b0ZDjSURikLgy3QhYcX8DvXo9q0qqK7,iv:kMjHIgcEOui/uY4XNOoggdwJPf+i4rZkblcWnfsL+lk=,tag:+y7zzX/fxyBq8SZE5xug3Q==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:YFVuk0WOo8jEoqtitGc=,iv:lw7rj6n7hbvXzghoQKwrtG7WGJluA6+oOmHxv2GrDaE=,tag:Bg0dXVmRZOlLTkTOvnxIgw==,type:str]
    SECRET_PRIVATE_DOMAIN: ENC[AES256_GCM,data:cA6oRO+iiQY=,iv:BWKm7X6DSXcTVd5kq15yYd8bI/P85ijPQxbvXUV5Uks=,tag:WK98BXNokrXpKWoxHc/O6w==,type:str]
    VOLSYNC_RESTIC_PASSWORD: ENC[AES256_GCM,data:+0gjhkySpDfE0yknNUbeI3F6pBcVr4FOag==,iv:wqsMKwv/RvU+UXhjYe4dZ+PZv8VrwpWEE67YNiAdjpY=,tag:epTvs6r6QxC8/PlnKFxeRg==,type:str]
    VOLSYNC_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:BQ2gZxFbPOCQF8YX0y4=,iv:Xi8aEpWAnXXVabj6l8UmTBIA3XZ9sk30WovX2+9EBFA=,tag:FJZJ0f3iou7K5Nvi1N+YMA==,type:str]
    VOLSYNC_MINIO_SECRET_KEY: ENC[AES256_GCM,data:GDUOVn3DYHL4fPIl8Ff2Nh0yt233cVZD7Q==,iv:vpkj925LjUee/6FoOsqZLf4YMkn4U6Zqf6lpjEuPdSk=,tag:eUwDpYB88mIEFytnZ9/l5A==,type:str]
    VOLSYNC_RESTIC_REPOSITORY: ENC[AES256_GCM,data:QJZ6bplmoiBQe6Byb8Rseml630jVfsjKCnrvb3QgVO51DmT+,iv:dNdsU3GvQFhCEYclgkee5mlXXJB6K1xDtXHnFquupnc=,tag:niJEtFqBrkc1iPHirGpS/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMGpOK0ZzQUxoQkJVOHhv
            WDhENitxS2d5SWtweXluejBEQjFYQmxEL3o4CnNyYThGMVVhaEFndndibU1hMWRm
            SEsxVVY0Wk54Y1JYeDZlK3VEV1JnY2MKLS0tIHY0bkxkVlZ1Y2RIWUNGNDdNbHBT
            a0dTRlNadE1WSndhdmF0emFGSWNKNncKaUnqzK9A4kHT//7VXm777MsqzIms6/Q7
            bIQ8ArETHsB8oN1DxKlQZgdhgBfrsFy2UGDdPtgbOhHzZ75J0tbPbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-29T23:06:21Z"
    mac: ENC[AES256_GCM,data:aQuzpMfyAjUgWmzFQvKjsKFuRCjMULhxU5wm57Xh3huPjdSbOBHJyBFKuGIjH0TYSiVmrrmJRvUWypMcZNEfOnyXL0XziSLTIBJn8kf6MTlas+1meI4TDWvh9TfOBwtW3u3ufsYYlcjq8MXjlxVaMtlKYCbaPjBwt5ykgJ8Rny4=,iv:AG2TMzxX4l5dE1kwCV0eEVkodVHFBYAyjRw1nmjbNY4=,tag:paXFpwQYf02Yv2SRsZbPVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
